# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - uv pip install --system .
      - uv pip install --system mkdocs mkdocs-material

mkdocs:
  configuration: documentation/mkdocs.yml
